### ISSUE TITLE
Manually updated to 2.1.0 and I'm still getting the error: `Error: Timeout reached` at `app.asar\preload.js:1:808619`

### ISSUE THREAD

**Issue by Deses** [KK-Designs/UpdateHub#100]
Hi! I updated the app to 2.1.0 by manually uninstalling 2.0.0 first because the update wasn't working.

I'm still getting the following error:
```
Error: Timeout reached
    at C:\Users\XXX\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619.
```
Attached is the log.
[app.log](https://github.com/KK-Designs/UpdateHub/files/12182942/app.log)

I'm also one of the spanish users that came from that blog post, but UpdateHub is set to English and I'm using dark mode.

```
UpdateHub
App version: 2.1.0
Chrome version: 114.0.5735.243
Node version: 18.15.0
Electron version: 25.3.1
OS version: 19045.3208
```

**Comment by KK-Designs** [comment]
Did you change your system language while UpdateHub was running?

**Comment by Deses** [comment]
Nope, I was just using the system normally.

**Comment by Deses** [comment]
Already closed?

**Comment by KK-Designs** [comment]
Well you said you fixed the issue, so we closed the issue as resolved
