### ISSUE TITLE
Getting the error ```Error: Timeout reached```  fixed

### ISSUE THREAD

**Issue by jcah73** [KK-Designs/UpdateHub#111]
Getting the error ```Error: Timeout reached
    at C:\Users\jcah7\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:808619```.

**Comment by KK-Designs** [comment]
What version of UpdateHub are you using?

**Comment by jcah73** [comment]
2.1 versión

**Comment by jcah73** [comment]
By the way, I'm on Windows 11 canary version... I don't know if it
influences

**Comment by KK-Designs** [comment]
Can you restart the app and try again? You can do this by force closing UpdateHub by holding shift and clicking the X button in the title bar or by right-clicking the tray icon and clicking close, then reopening UpdateHub.

**Comment by jcah73** [comment]
I uninstalled and re-installed the application and nothing

**Comment by jcah73** [comment]
I fix the problem with cmd as administrator and then:

winget install Microsoft.DotNet.SDK.7
winget install Microsoft.DotNet.DesktopRuntime.7
winget install Microsoft.DotNet.AspNetCore.7
winget install Microsoft.DotNet.Runtime.7
winget install Microsoft.DotNet.DesktopRuntime.Preview


and now works perfectly. in case it helps and if it works for you
