### ISSUE TITLE
`APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH (0x8A15005E)` Error when updating an app

### ISSUE THREAD

**Issue by jonno-96** [KK-Designs/UpdateHub#186]
Getting the error `APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH (0x8A15005E)` when installing an app.

I'm getting this error on all of the programs on my PC which UpdateHub says require an update. However, if I open any of the programs and check for updates under the Updates or About links, I am able to update my programs without any error message.

**Comment by KK-Designs** [comment]
It looks like you are using an older version of WinGet, which our app uses to scan for updates. You can download the latest version here: [https://aka.ms/getwinget](https://aka.ms/getwinget "Download WinGet"). This is an official Microsoft domain and file. After installing, if you see a message saying "For proper functioning of the app, try to launch a Windows app package.", just ignore it and close the window.

**Comment by KK-Designs** [comment]
Closing as completed
