### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by zolive59** [KK-Designs/UpdateHub#19]
Getting the error ```Error: Timeout reached
    at C:\Users\zoliv\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325```.

**Comment by zolive59** [comment]
[app.log](https://github.com/KK-Designs/UpdateHub/files/12157844/app.log)

**Comment by KK-Designs** [comment]
fixed
