### ISSUE TITLE
`APPINSTALLER_CLI_ERROR_SHELLEXEC_INSTALL_FAILED (0x8A150006)` Error when updating an app

### ISSUE THREAD

**Issue by vividvibe** [KK-Designs/UpdateHub#217]
Getting the error `APPINSTALLER_CLI_ERROR_SHELLEXEC_INSTALL_FAILED (0x8A150006)` when installing an app.

### Debug info:
App version: 2.2.0
Device ID: b49b8a06-e077-4179-b889-f3600d56a009
OS version: 22621.2215
Electron version: 26.1.0
Node version: 18.16.1
Chrome version: 116.0.5845.97

**Comment by KK-Designs** [comment]
This usually means that the app you are trying to update is open. Could you try closing it and updating it again?

**Comment by vividvibe** [comment]
> This usually means that the app you are trying to update is open. Could you try closing it and updating it again?

It wasn't open but eventually the issue resolved itself.  I didn't even have to relaunch the app.  Weird right?

**Comment by KK-Designs** [comment]
Yeah, but hey it works now! Closing as resolved
