### ISSUE TITLE
Getting the error ```Error: EBUSY: resource busy or locked, unlink 'C:\Users\Utilisateur\AppData\Roaming\update-hub\latest.exe'```

### ISSUE THREAD

**Issue by Orbis2** [KK-Designs/UpdateHub#244]
Getting the error ```Error: EBUSY: resource busy or locked, unlink 'C:\Users\Utilisateur\AppData\Roaming\update-hub\latest.exe'
    at Object.unlinkSync (node:fs:1808:3)
    at window.<computed> (C:\Users\Utilisateur\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:353481)```.

**Comment by KK-Designs** [comment]
As per [v2.2.1 notes](https://github.com/KK-Designs/UpdateHub/releases/tag/v2.2.1),

> Also if you get an error that looks like `Error: EBUSY: resource busy or locked, unlink ...` just reload the app via <kbd>CTRL</kbd> + <kbd>R</kbd>, and you can continue using it. This will be fixed in the next release.

**Comment by KK-Designs** [comment]
Should be fixed in the latest release 👍
