### ISSUE TITLE
`APPINSTALLER_CLI_ERROR_NO_APPLICATIONS_FOUND (0x8A150014)` Error when updating an app

### ISSUE THREAD

**Issue by Imbil** [KK-Designs/UpdateHub#339]
Getting the error `APPINSTALLER_CLI_ERROR_NO_APPLICATIONS_FOUND (0x8A150014)` when installing an app.

### Debug info:
App version: 2.2.3
Device ID: fb4e7c74-c80a-4e1d-9205-97dc14cb1c9c
OS version: 19045.3570
Electron version: 26.2.1
Node version: 18.16.1
Chrome version: 116.0.5845.188

**Comment by Imbil** [comment]
![Vlc error when updating](https://github.com/KK-Designs/UpdateHub/assets/92493938/f8d7fcac-be5a-437e-ac66-c0cabd57be87)

![vlc update](https://github.com/KK-Designs/UpdateHub/assets/92493938/796bacf1-aab8-4ade-85b2-3784a4284f83)

**Comment by Imbil** [comment]
I hope this can help.

**Comment by KK-Designs** [comment]
See #269
