### ISSUE TITLE
Launching app in administrator mode still yields error "This feature requires administrator mode" when clicking "ms store apps" or "windows update"

### ISSUE THREAD

**Issue by clorteau** [KK-Designs/UpdateHub#47]
As the title says. I launch the app in administrator mode yet opening the "ms store apps" or "windows update" tabs still yields the error "This feature requires administrator mode" .

I could reproduce the error on 2 different computers. Windows version: Windows 11 home version 22H2 builds 22624.1755 and 22631.2050.

**Comment by Nicbobbo6** [comment]
Same error here, Windows 11 pro 22H2 22621.1992

**Comment by KK-Designs** [comment]
Could you try force-closing UpdateHub and then starting it as administrator? You can force close by holding shift and clicking the X button in the title bar or by right-clicking the tray icon and clicking close.

**Comment by clorteau** [comment]
That worked, thank you.

**Comment by Nicbobbo6** [comment]
Same here, thanks

**Comment by KK-Designs** [comment]
We are working on a more user-friendly way to do this, coming in the next update
