### ISSUE TITLE
"Update available" button never shows

### ISSUE THREAD

**Issue by clorteau** [KK-Designs/UpdateHub#48]
The "apps" tab does show available updates yet the "update available" button never shows, even after force closing like the readme says.

I could reproduce the error on 2 different computers. Windows version: Windows 11 home version 22H2 builds 22624.1755 and 22631.2050.

**Comment by KK-Designs** [comment]
The "Update available" button in the sidebar is to update UpdateHub itself, not the apps shown in the list. If that button doesn't show it means you are already on the latest version of UpdateHub.

**Comment by clorteau** [comment]
Oh I thought it was a button to apply all found update. Such a button would be nice btw.

**Comment by KK-Designs** [comment]
Will try to add an "Update All" in later versions
