### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by temis01** [KK-Designs/UpdateHub#6]
Getting the error ```Error: Timeout reached
    at C:\Users\temis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325```.

**Comment by KK-Designs** [comment]
Hello! In order for us to solve this issue, we need a log file to see what's happening. It is located at `C:\Users\temis\AppData\Roaming\update-hub\app.log`. Upload that file here, and we can try to fix the error.

**Comment by temis01** [comment]
[app.log](https://github.com/KK-Designs/UpdateHub/files/12117705/app.log)

**Comment by KK-Designs** [comment]
Can you retry by clicking the "Check for update" button on the app update page?

![image](https://github.com/KK-Designs/UpdateHub/assets/71038229/0a80483d-5718-4a1a-a1ea-81a14cc115b1)

**Comment by temis01** [comment]
Same result after <check for update>
[app.log](https://github.com/KK-Designs/UpdateHub/files/12121539/app.log)

An unexpected error occurred
Error: Error: Timeout reached at C:\Users\temis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325

**Comment by temis01** [comment]
if I right click on the lower part of the system tray icon I can't reach the exit/close part of the menu
doing the same with any other icon in systray gives me the whole menu.

![right click on updatehub system tray icon to close the app](https://github.com/KK-Designs/UpdateHub/assets/75322684/408e0083-6aab-4274-8783-97c7fc558b99)

**Comment by KK-Designs** [comment]
> if I right click on the lower part of the system tray icon I can't reach the exit/close part of the menu doing the same with any other icon in systray gives me the whole menu.
> 
> ![right click on updatehub system tray icon to close the app](https://user-images.githubusercontent.com/75322684/255125735-408e0083-6aab-4274-8783-97c7fc558b99.jpg)

We'll try to find a fix for this, this shouldn't happen.

**Comment by KK-Designs** [comment]
> Same result after [app.log](https://github.com/KK-Designs/UpdateHub/files/12121539/app.log)
> 
> An unexpected error occurred Error: Error: Timeout reached at C:\Users\temis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325

Can you try opening up cmd prompt and type in `winget upgrade` and see if that outputs anything? Whats happening is that UpdateHub is executing the command and is waiting for data. If UpdateHub doesn't receive anything after 100 seconds it quits because their is probably something wrong.

**Comment by temis01** [comment]
winget upgrade : any and every app is up to date

**Comment by temis01** [comment]
I pinned update-hub to the taskbar.
When I click the pinned icon to start update-hub I get a cursor animation for a while and update-hub windows shows up
Using the system tray icon shows update-hub instantly

I am not sure this is an issue or an ergonomic choice to use update-hub

**Comment by KK-Designs** [comment]
Ok so we have some good news. We fixed the system tray context menu, which should be fixed in the next update (`2.0.1`) coming soon. It looks like you fixed the `Error: Timeout reached` error so that's good. The reason why the cursor animation shows for a while and then update-hub's window shows up is because of how the taskbar works. When you click it, it opens a new instance of the app. However, if you already have UpdateHub opened we don't want to make a new window. Instead, we close the one from the taskbar click and focus the already opened window. The system tray icon just focuses the window. There's no way to bypass the cursor animation from the taskbar click.

**Comment by temis01** [comment]
What do you mean "I fixed the time out error" ?
I had to update the apps to get rid of the error ... why would I want to use an updater if I have to update the apps myself ?

About the pinned icon :
- I think that if I click on the pinned icon the windows should show up before any update process happen so the user is not confused whether the app is ok or not
- right clicking on a specific task from the systray icon or pinned icon and launch the selected update process before the window shows up seems more acceptable since a task was selected

About the pinned and systray icon :
- right clicking on tasks like windows update or app store update has no point in the right click menu since they will irrevocably end up with an error <This feature requires administrator mode> and the app will need to restart in admin mode + close the systray icon before it's possible see below

To be able to use update-hub as admin not only the the app must be closed but also systray icon or I get admin mode must be activate error

**Comment by KK-Designs** [comment]
I think I've found out why you're getting the Timeout error. As seen in the screenshot below, the app starts checking for app updates once it gets the header text, which is Name Id Version, etc. But in the screenshot you sent of the command line the output isn't in English, so UpdateHub thinks that the data was never outputted and is still loading. The reason why you get the Timeout is because it took too long and the app knew something was wrong but it didn't know what. I'm going to fix this as well in the next update. I'll let you know once it's released.

![Screenshot_20230722_010005_File Manager +.png](https://github.com/KK-Designs/UpdateHub/assets/71038229/9e9f029b-6f85-443c-b8bf-663267362a34)

**Comment by AngelR0909** [comment]
Hi

I had the issue.
When I send 'winget upgrade' in my CMD, it prompt me to read (or accept) licence !!!
![image](https://github.com/KK-Designs/UpdateHub/assets/3276416/9e7d0828-fb42-4f09-8373-02e9fce470b1)

When I accept it by typing 'Y', winget command work, and UpdateHub too !

**Comment by temis01** [comment]
about the admin mode required for app store + windows update :
why don't you offer to restart the app in admin mode ?

which app installed on the pc are supposed to be updated by update-hub ?

**Comment by KK-Designs** [comment]
> Same result after <check for update>
> [app.log](https://github.com/KK-Designs/UpdateHub/files/12121539/app.log)
> 
> An unexpected error occurred
> Error: Error: Timeout reached at C:\Users\temis\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325

Try updating to the latest version of UpdateHub and try again.

**Comment by KK-Designs** [comment]
> about the admin mode required for app store + windows update :
> why don't you offer to restart the app in admin mode ?
> 
> which app installed on the pc are supposed to be updated by update-hub ?

We will try to add a restart as administrator button in future updates. I don't understand your last question though.

**Comment by temis01** [comment]
> > about the admin mode required for app store + windows update :
> > why don't you offer to restart the app in admin mode ?
> > which app installed on the pc are supposed to be updated by update-hub ?
> 
> We will try to add a restart as administrator button in future updates. I don't understand your last question though.

Last question means : is update-hub supposed to offer an update for any and every application installed on my rig or does it have a specific scope ?

**Comment by KK-Designs** [comment]
UpdateHub will display every outdated app that it can find on your PC. If you don't want to update an app and don't want it to show in the list, you can click on the "Ignore" button. You can see ignored items by clicking the "See ignored outdated items" on the settings page.

**Comment by jcah73** [comment]
I fix the Error: Timeout reached. I put cmd as administrator and then:

winget install Microsoft.DotNet.SDK.7
winget install Microsoft.DotNet.DesktopRuntime.7
winget install Microsoft.DotNet.AspNetCore.7
winget install Microsoft.DotNet.Runtime.7
winget install Microsoft.DotNet.DesktopRuntime.Preview

and now works perfectly. in case it helps and if it works for you

**Comment by KK-Designs** [comment]
The latest version fixes the main reason of this issue, so closing
