### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by Yassas11** [KK-Designs/UpdateHub#7]
Getting the error ```Error: Timeout reached
    at C:\Users\yassa\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325```.

**Comment by KK-Designs** [comment]
This error has to do with the system language setting. Please temporarily change it to English while we work on a fix.

**Comment by KK-Designs** [comment]
Closing as it is a duplicate of #6

**Comment by KK-Designs** [comment]
Changing issue closing status to duplicate

**Comment by KK-Designs** [comment]
Fixed in v2.1.0
